#!/bin/bash
root -b -l -q 'figefff.C'
root -b -l -q 'figg1g2Fiber2.C'
root -b -l -q 'fignonconsvf.C'
root -b -l -q 'fignsncpbwo4L.C'
root -b -l -q 'figscvniFiber1.C'
root -b -l -q 'figthreeresPbWOS.C'
root -b -l -q 'figESC.C'
root -b -l -q 'figg1g2SampL.C'
root -b -l -q 'fignsncFiber1.C'
root -b -l -q 'fignsncpbwo4S.C'
root -b -l -q 'figthreeresFiber1.C'
root -b -l -q 'figthreeresSampL.C'
root -b -l -q 'figescvf.C'
root -b -l -q 'figg1g2SampS.C'
root -b -l -q 'fignsncFiber1timing.C'
root -b -l -q 'fignsncSampL.C'
root -b -l -q 'figthreeresFiber2.C'
root -b -l -q 'figthreeresSampS.C'
root -b -l -q 'figg1g2Fiber1.C'
root -b -l -q 'figNONCONS.C'
root -b -l -q 'fignsncFiber2.C'
root -b -l -q 'fignsncSampS.C'
root -b -l -q 'figthreeresPbWOL.C'
root -b -l -q 'figtimingFiber1.C'


